In [1]:
import numpy as np
from numpy.linalg import inv
import random
import scipy
from scipy import linalg#LU decomposition
import sklearn # Dimensionality reduce
from sklearn import decomposition # Dimensionality reduce with SVD

In [2]:
I= np.identity(3)

# Matrix Decomposition/Factorization

**Matrix decompositions are methods that reduce a matrix into constituent
parts that make it easier to calculate more complex matrix operations**

### 1. LU Decomposition
**A = L · U · P**
- The LU decomposition is for **square matrices** and decomposes a matrix into L and U components (**L is lower triangle** and **U is Upper Triangle**)
- LU decomposition can fail for those matrices that cannot be decomposed or decomposed easily --> LU decomposition with partial pivoting.

In [3]:
A= np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
P,L,U= scipy.linalg.lu(A) # LU decomposition

In [5]:
P

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [6]:
L

array([[1.        , 0.        , 0.        ],
       [0.14285714, 1.        , 0.        ],
       [0.57142857, 0.5       , 1.        ]])

In [7]:
U

array([[7.        , 8.        , 9.        ],
       [0.        , 0.85714286, 1.71428571],
       [0.        , 0.        , 0.        ]])

Reconstruct Matrix

In [8]:
P@L@U

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [9]:
scipy.linalg.lu_factor(A) #LU_factor

<ipython-input-9-28c89a10a3d4>:1: LinAlgWarning: Diagonal number 3 is exactly zero. Singular matrix.
  scipy.linalg.lu_factor(A) #LU_factor


(array([[7.        , 8.        , 9.        ],
        [0.14285714, 0.85714286, 1.71428571],
        [0.57142857, 0.5       , 0.        ]]),
 array([2, 2, 2], dtype=int32))

Another decomposition but only return values

In [10]:
LU= scipy.linalg.lu_factor(A)[0]

<ipython-input-10-7ffa236cb0ed>:1: LinAlgWarning: Diagonal number 3 is exactly zero. Singular matrix.
  LU= scipy.linalg.lu_factor(A)[0]


In [11]:
U=np.triu(LU)
U

array([[7.        , 8.        , 9.        ],
       [0.        , 0.85714286, 1.71428571],
       [0.        , 0.        , 0.        ]])

In [12]:
L=LU-U+I
L

array([[1.        , 0.        , 0.        ],
       [0.14285714, 1.        , 0.        ],
       [0.57142857, 0.5       , 1.        ]])

### 2. QR Decomposition
**A = Q · R**
- QR decomposition is for **n × m matrices** (not limited to square matrices) and decomposes a matrix into **Q and R components**
- As with LU decomposition, It can be used to solve systems of linear equations like least square problems and to find eigenvalues of a general matrix.

In [13]:
A= np.array([[1,2],[3,4],[5,6]])
A # 3 row 2 col

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
Q,R= np.linalg.qr(A, 'complete')

In [15]:
Q  #square of 3 rows

array([[-0.16903085,  0.89708523,  0.40824829],
       [-0.50709255,  0.27602622, -0.81649658],
       [-0.84515425, -0.34503278,  0.40824829]])

In [16]:
R # 3 row, 2 cols

array([[-5.91607978, -7.43735744],
       [ 0.        ,  0.82807867],
       [ 0.        ,  0.        ]])

Reconstruct matrix

In [17]:
Q@R

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

### 3. Cholesky Decomposition
- The Cholesky decomposition is for **square symmetric matrices** where all values are greater than zero, so-called **positive definite matrices**
- Cholesky decomposition is nearly twice as efficient as the LU decomposition 

In [18]:
A= np.array([[2,1,1],[1,2,1],[1,1,2]])

In [19]:
A

array([[2, 1, 1],
       [1, 2, 1],
       [1, 1, 2]])

In [20]:
L= np.linalg.cholesky(A)
L

array([[1.41421356, 0.        , 0.        ],
       [0.70710678, 1.22474487, 0.        ],
       [0.70710678, 0.40824829, 1.15470054]])

Construct matrix

In [21]:
L@(L.T)

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

### 4. Eigendecomposition
- **A = Q · Λ · QT** Q: vectors, Λ: diagonal matrix of values
- decomposing a square matrix into a set of **eigenvectors** and **eigenvalues**
- **Eigenvectors (v)** are unit vectors, which means that their length or magnitude is equal to 1.0. They are often referred as right vectors, which simply means a column vector **A@v = λ*v**
- **Eigenvalues (λ)** are coefficients applied to eigenvectors that give the vectors their length or magnitude
- A matrix that has only positive eigenvalues is referred to as a positive definite matrix, whereas if the eigenvalues are all negative, it is referred to as a negative definite matrix.

In [22]:
A

array([[2, 1, 1],
       [1, 2, 1],
       [1, 1, 2]])

In [23]:
values, vectors= np.linalg.eig(A) # factorize

In [24]:
values #λ

array([1., 4., 1.])

In [25]:
vectors #v

array([[-0.81649658,  0.57735027, -0.32444284],
       [ 0.40824829,  0.57735027, -0.48666426],
       [ 0.40824829,  0.57735027,  0.81110711]])

Confirm A@v = λ*v

In [26]:
vectors[:,0] # (v) 1st column

array([-0.81649658,  0.40824829,  0.40824829])

In [28]:
A@vectors[:,0]# confirming A@v 

array([-0.81649658,  0.40824829,  0.40824829])

In [29]:
values[0]*vectors[:,0]# confirming λv

array([-0.81649658,  0.40824829,  0.40824829])

Reconstruct matrix

In [30]:
Q= vectors
Q

array([[-0.81649658,  0.57735027, -0.32444284],
       [ 0.40824829,  0.57735027, -0.48666426],
       [ 0.40824829,  0.57735027,  0.81110711]])

In [31]:
R= inv(Q)
R

array([[-8.16496581e-01,  7.14434508e-01,  1.02062073e-01],
       [ 5.77350269e-01,  5.77350269e-01,  5.77350269e-01],
       [-3.79911345e-32, -7.70551750e-01,  7.70551750e-01]])

In [32]:
L= np.diag(values)
L

array([[1., 0., 0.],
       [0., 4., 0.],
       [0., 0., 1.]])

In [33]:
Q@L@R

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

### 5. Singular- value Decomposition (SVD)
- **A = U · Σ · Vt**
- **A(m x n)** = U(m × m) · Σ(m × n) · V T (n × n)
- **A** is the real n × m matrix 
- **U** is an m × m matrix
- **Σ** is an m × n diagonal matrix
- **Vt** is the V transpose of an n × n matrix 

In [34]:
A= np.array([
    [1,2],
    [3,4],
    [5,6]]) # 3 x 2 matrix

In [35]:
U, s, V= scipy.linalg.svd(A)

In [36]:
U # 3 x 3 matrix

array([[-0.2298477 ,  0.88346102,  0.40824829],
       [-0.52474482,  0.24078249, -0.81649658],
       [-0.81964194, -0.40189603,  0.40824829]])

In [37]:
s # 2 elements of diagonal matrix

array([9.52551809, 0.51430058])

In [38]:
V # 2 x 2 matrix

array([[-0.61962948, -0.78489445],
       [-0.78489445,  0.61962948]])

Reconstruct matrix

In [39]:
A.shape

(3, 2)

In [40]:
sigma= np.zeros((3,2)) # create Σ(m × n)
sigma

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [41]:
np.diag(s)

array([[9.52551809, 0.        ],
       [0.        , 0.51430058]])

In [42]:
sigma[:2,:2]=np.diag(s)
sigma

array([[9.52551809, 0.        ],
       [0.        , 0.51430058],
       [0.        , 0.        ]])

In [43]:
U@sigma@V

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

### 6. Dimensionality Reduction
- Data with a large number of features, such as more features (columns) than observations (rows) may be reduced to a smaller subset of features that are most relevant to the prediction problem.
- To do this we can perform an SVD operation on the original data and select the top k largest singular values in Σ. These columns can be selected from Σ and the rows selected from V T
- dense summary of the matrix or a projection T = U · Σk or T = A · VkT

In [44]:
A = np.array([
[1,2,3,4,5,6,7,8,9,10],
[11,12,13,14,15,16,17,18,19,20],
[21,22,23,24,25,26,27,28,29,30]])
A # 3 x 10

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [45]:
U,s,V= scipy.linalg.svd(A)

In [46]:
A.shape

(3, 10)

In [47]:
U.shape

(3, 3)

In [48]:
sigma= np.zeros((3,10)) # create Σ(m × n)
sigma

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [49]:
sigma[:3,:3] =np.diag(s)
sigma.shape

(3, 10)

In [50]:
V.shape

(10, 10)

In [51]:
U@sigma@V

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25., 26., 27., 28., 29., 30.]])

Select features manual

In [52]:
n_elements= 2 # select features

In [56]:
U.shape

(3, 3)

In [53]:
sigma= sigma[:,:n_elements]
sigma.shape # reduce number of cols of  Σk

(3, 2)

In [55]:
V= V[:n_elements,:] # reduce number of column Vk
V.shape

(2, 10)

In [57]:
U@sigma@V# reconstruct full matrix

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25., 26., 27., 28., 29., 30.]])

In [58]:
U@sigma #dense summary of the matrix or a projection T = U · Σk

array([[-18.52157747,   6.47697214],
       [-49.81310011,   1.91182038],
       [-81.10462276,  -2.65333138]])

In [59]:
A@(V.T)  # T = A · VkT

array([[-18.52157747,   6.47697214],
       [-49.81310011,   1.91182038],
       [-81.10462276,  -2.65333138]])

Select feature using scikit-learn

In [67]:
svd= sklearn.decomposition.TruncatedSVD(n_components=2)

In [68]:
svd.fit(A)

TruncatedSVD()

In [69]:
svd.transform(A)

array([[18.52157747,  6.47697214],
       [49.81310011,  1.91182038],
       [81.10462276, -2.65333138]])

### 7.Pseudoinverse
**The pseudoinverse is the generalization of the matrix inverse for square matrices to rectangular
matrices where the number of rows and columns are not equal**

- **A+ = V · D+ · Ut**
- **A+ = Vt. Dt . Ut** (manually calculate from SVD)
- The pseudoinverse provides one way of solving the linear regression equation, specifically when there are more rows than there are columns, which is often the case

In [3]:
A= np.array([[0.1,0.2],[0.3,0.4],[0.5,0.6],[0.7,0.8]])
A

array([[0.1, 0.2],
       [0.3, 0.4],
       [0.5, 0.6],
       [0.7, 0.8]])

In [5]:
B=np.linalg.pinv(A) # calculate pseudoinverse
B

array([[-1.00000000e+01, -5.00000000e+00,  1.28757642e-14,
         5.00000000e+00],
       [ 8.50000000e+00,  4.50000000e+00,  5.00000000e-01,
        -3.50000000e+00]])

In [20]:
(B@A).round(0) # Cross check inverse matrix

array([[1., 0.],
       [0., 1.]])

Calculate pseudoinverse manually from SVD

**A+ = Vt. Dt . Ut**
- D is diag matrix from 1/s 

In [18]:
U,s,V= scipy.linalg.svd(A) # factorize SVD

In [22]:
s

array([1.42690955, 0.06268282])

In [21]:
d=1/s
d

array([ 0.70081527, 15.95333376])

In [24]:
D= np.zeros(A.shape)
D

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [26]:
D[:2,:2]=np.diag(d)

In [27]:
D

array([[ 0.70081527,  0.        ],
       [ 0.        , 15.95333376],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ]])

In [29]:
B=(V.T)@(D.T)@(U.T)
B

array([[-1.00000000e+01, -5.00000000e+00,  1.28565458e-14,
         5.00000000e+00],
       [ 8.50000000e+00,  4.50000000e+00,  5.00000000e-01,
        -3.50000000e+00]])