In [1]:
import numpy as np

In [2]:
from numpy.linalg import norm # norm
from numpy.linalg import inv # inverse
from numpy.linalg import det # determinant
from numpy.linalg import matrix_rank # rank
import scipy.sparse as sparse # sparse matrix
import math
import random

### Vector 

**Vector norm: The length of a vector is a nonnegative number that describes the extent of the vector in space, and is sometimes referred to as the vector’s magnitude or the norm.**

In [3]:
vn= np.array([1,2,3])

In [4]:
vn1= np.random.randint(10,50, size=5)
vn1

array([49, 43, 22, 47, 23])

In [5]:
vn.ndim

1

In [6]:
vn.shape

(3,)

**Arithmetic Operation**

In [7]:
vn+vn

array([2, 4, 6])

In [8]:
vn-vn

array([0, 0, 0])

In [9]:
vn*10

array([10, 20, 30])

**Dot product**

In [10]:
np.dot(vn,vn)

14

In [11]:
vn@vn

14

**Norm/Magnitude**

In [12]:
norm(vn,1) #L1 Norm, the sum of the absolute vector values, Manhattan Distance

6.0

In [13]:
norm(vn) #L2 Norm, calculates the distance of the vector coordinate from the origin of the vector, Euclidean distance

3.7416573867739413

In [14]:
norm(vn,np.inf)#max norm, max value in vector

3.0

### Matrix

**Transpose matrix**

In [15]:
A=np.random.randint(10,20,(3,2))
A # A 3 rows, 2 columns

array([[14, 11],
       [13, 15],
       [18, 18]])

In [16]:
(A.T).T

array([[14, 11],
       [13, 15],
       [18, 18]])

**Type of matrix**

In [17]:
T=np.random.randint(10,20,(3,3))
T

array([[19, 11, 10],
       [12, 15, 10],
       [19, 10, 19]])

In [18]:
np.triu(T)

array([[19, 11, 10],
       [ 0, 15, 10],
       [ 0,  0, 19]])

In [19]:
np.tril(T)

array([[19,  0,  0],
       [12, 15,  0],
       [19, 10, 19]])

In [20]:
np.diag(T)

array([19, 15, 19])

**Matrix multiphication**

**C(m,k)= A(m,n).B(n,k)**
- A columns= B rows
- result is matrix with m rows and k columns

In [21]:
A=np.array([[1,2],[3,4],[5,6]])
A # A 3 rows, 2 columns

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
B=np.array([[1,2],[3,4]])
B # 2 rows, 2 columns

array([[1, 2],
       [3, 4]])

In [23]:
A[0] # 1st row

array([1, 2])

In [24]:
B.T[0] # 1st columns

array([1, 3])

In [25]:
A[0].dot(B.T[0]) # 1st value in 1st row

7

In [26]:
A[0].dot(B.T[1]) # 2nd value in 1st row

10

In [27]:
A@B

array([[ 7, 10],
       [15, 22],
       [23, 34]])

In [28]:
np.matmul(A,B)

array([[ 7, 10],
       [15, 22],
       [23, 34]])

**Determinant**
- The determinant of a square matrix is a scalar representation of the volume of the matrix.
- Determinant describes the way a matrix will scale another matrix when they are multiplied together

In [29]:
det(T)

1447.0

**Rank**
- The rank of a matrix is the estimate of the number of linearly independent rows or columns in a matrix.
- Rank is not the number of dimensions of the matrix

In [30]:
matrix_rank(T)

3

**Inverse**

In [31]:
C=np.array([[1,2,5],[3,4,4],[5,6,6]])

In [32]:
C1= inv(C)
C1

array([[ 0.        , -3.        ,  2.        ],
       [-0.33333333,  3.16666667, -1.83333333],
       [ 0.33333333, -0.66666667,  0.33333333]])

In [33]:
(C@C1).round(1)

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [-0.,  0.,  1.]])

In [34]:
C[0].dot(C1.T[0])

0.9999999999999999

In [35]:
I= np.array([[1,0,0],[0,1,0],[0,0,1]])

In [36]:
C[0].dot(I.T[0])

1

### Sparse Matrix

- A sparse matrix is a matrix that is comprised of mostly zero values. 
- Sparse matrices are distinct from matrices with mostly non-zero values, which are referred to as dense matrices

In [37]:
sp=np.array([[8,0,0,6,0,0],[0,0,9,0,0,4],[0,0,0,3,0,0]])

In [38]:
csr= sparse.csr_matrix(sp) # matrix --> CSR format
print(csr)

  (0, 0)	8
  (0, 3)	6
  (1, 2)	9
  (1, 5)	4
  (2, 3)	3


In [39]:
csr.data # all non-zero data in the matrix 

array([8, 6, 9, 4, 3], dtype=int32)

In [40]:
csr.indices # column position of all non-zero data in matrix

array([0, 3, 2, 5, 3], dtype=int32)

In [41]:
csr.indptr 
# for each row, correspondent position of first non-zero value in data, length of data

array([0, 2, 4, 5], dtype=int32)

In [42]:
csr.todense() # convert to spare matrix from csr

matrix([[8, 0, 0, 6, 0, 0],
        [0, 0, 9, 0, 0, 4],
        [0, 0, 0, 3, 0, 0]], dtype=int32)

In [43]:
csr_from_shape=sparse.csr_matrix((csr.data,csr.indices,csr.indptr),shape=(3,10)) 
# csr format (explicit shape) --> CSR format
csr_from_shape.indptr

array([0, 2, 4, 5], dtype=int32)